//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteDisksNET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Issue
    {
        public Issue()
        {
            this.Comments = new HashSet<Comment>();
            this.IssueRoleChecks = new HashSet<IssueRoleCheck>();
        }
    
        public int Id { get; set; }
        public string IssueTitle { get; set; }
        public string Description { get; set; }
        public int TaskId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual Task Task { get; set; }
        public virtual ICollection<IssueRoleCheck> IssueRoleChecks { get; set; }
    }
}
