//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteDisksNET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssueRoleCheck
    {
        public int Id { get; set; }
        public int IssueId { get; set; }
        public int RoleId { get; set; }
        public bool IdDone { get; set; }
    
        public virtual Issue Issue { get; set; }
        public virtual Role Role { get; set; }
    }
}
