//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteDisksNET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.CommentRoles = new HashSet<CommentRole>();
        }
    
        public int Id { get; set; }
        public string RoleName { get; set; }
    
        public virtual ICollection<CommentRole> CommentRoles { get; set; }
        public virtual IssueRoleCheck IssueRoleCheck { get; set; }
    }
}
